name: "Pull Request Workflow"

on:
  pull_request:
  workflow_dispatch:

jobs:
    format-check:
      uses: ./.github/workflows/black-fmt-check.yml
    linting-check:
      uses: ./.github/workflows/pylint-check.yml
    build-docker-image:
        needs: 
          - format-check
          - linting-check
        uses: ./.github/workflows/docker-build.yml
        secrets: inherit
    run-terraform-plan:
        needs: build-docker-image
        uses: ./.github/workflows/terraform-plan.yml
        permissions:
          pull-requests: write
          contents: read
        secrets: inherit
