name: "Pull Request Workflow"

on:
  pull_request:
  workflow_dispatch:

jobs:
    build-docker-image:
        uses: ./.github/workflows/docker/build.yml
    run-terraform-plan:
        uses: ./.github/workflows/terraform/plan.yml